services:
  backend:
    build: ./Cria-o_API
    container_name: sispar_backend
    ports:
      - "5000:5000"
    volumes:
      - ./Cria-o_API:/app
    environment:
      - FLASK_ENV=development
    env_file:
      - ./Cria-o_API/.env  # garante que o backend leia sua variável do banco
    depends_on:
      - sispar-db

  frontend:
    build: ./Projeto-Sispar
    container_name: sispar_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  sispar-db:
    image: mysql:8.0
    container_name: sispar-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sispar
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
